--- #YAML:1.0
name:               Oracle-Trace
version:            1.08
abstract:           Perl Module for parsing Oracle Trace files
author:
    - Richard Foley <oracle.trace@rfi.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
